# Generated by Django 4.0.6 on 2022-07-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_order_detail_product_order_detail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='product',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.product'),
            preserve_default=False,
        ),
    ]
