# Generated by Django 4.0.6 on 2022-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_order_detail_product_order_detail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
