# Generated by Django 4.0.6 on 2022-07-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='product',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='order_detail',
        ),
    ]
