# Generated by Django 4.1 on 2022-08-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addres',
            field=models.TextField(blank=True, help_text='آدرس خود را وارد کنید', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='User/image'),
        ),
        migrations.AddField(
            model_name='user',
            name='nation_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
