# Generated by Django 4.1 on 2022-08-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0002_user_addres_user_image_user_nation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='User/image'),
        ),
    ]
