# Generated by Django 4.1 on 2022-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=22, max_length=15),
            preserve_default=False,
        ),
    ]
