# Generated by Django 4.0.6 on 2022-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
